---
train:
  params:
    batch_size: 80
    epoch: 10
    lr: 0.0001
    decay: 1
    decay_step: 10
    loss: L1Loss
  save:
    save_path: "/home/xyz/gz/GazeBenchmark/GazeZone/TEST/ETH"
    model_name: PureGaze
    step: 1
  data:
    image: "/home/xyz/gz/datasets/ETH-XGaze/Image/train"
    label: "/home/xyz/gz/datasets/ETH-XGaze/Label1/train.label"
  pretrains: "None"

valid:
   load:
      begin_step: 4
      end_step: 20
      steps: 4
      load_path: "/home/cyh/GazeBenchmark/exp/Implementation/Gaze360-eth"
      model_name: Gaze360
   data:
      image: "/home/cyh/GazeDataset20200519/FaceBased/ETH-Gaze/Image/train"
      label: "/home/cyh/GazeDataset20200519/FaceBased/ETH-Gaze/Label/test.label"

test:
   load:
      begin_step: 20
      end_step: 20
      steps: 4
      load_path: "/home/xyz/gz/GazeBenchmark/exp/PureGaze/Test/eth3_triplet"
      model_name: Gaze360
   data:
      image: "/home/xyz/gz/datasets/ETH-XGaze/Image/test"
      label: "/home/xyz/gz/datasets/ETH-XGaze/Label/test.label"
cross:
  save_name: cross-mpii-new
  load:
      begin_step: 16
      end_step: 16
      steps: 4
      load_path: "/home/xyz/gz/GazeBenchmark/exp/PureGaze/Test/eth"
      load_name: False
      model_name: Gaze360
  data:
      image: "/home/cyh/GazeDataset20200519/FaceBased/MPIIFaceGaze/Image"
      label: "/home/cyh/GazeDataset20200519/FaceBased/MPIIFaceGaze/Label"

# image: "/home/cyh/GazeDataset20200519/FaceBased/EyeDiap/Image"
# label: "/home/cyh/GazeDataset20200519/FaceBased/EyeDiap/ClusterLabel"

reader: reader_eth
device: 0
