---
train:
  params:
    batch_size: 80
    epoch: 10
    lr: 0.0001
    decay: 1
    decay_step: 10
    loss: L1Loss
  save:
    save_path: "/home/xyz/gz/GazeBenchmark/GazeZone/TEST/ETH"
    model_name: ETH
    step: 1
  data:
    image: "/home/xyz/gz/datasets/ETH-XGaze/Image/train"
    label: "/home/xyz/gz/datasets/ETH-XGaze/Label1/train.label"
  pretrains: "None"

valid:
   load:
      begin_step: 4
      end_step: 20
      steps: 4
      load_path: "/home/xyz/gz/GazeBenchmark/GazeZone/TEST/ETH"
      model_name: Gaze360
   data:
      image: "/home/xyz/gz/datasets/ETH-XGaze/Image/test"
      label: "/home/xyz/gz/datasets/ETH-XGaze/Label/test.label"

test:
   load:
      begin_step: 20
      end_step: 20
      steps: 4
      load_path: "/home/xyz/gz/GazeBenchmark/exp/PureGaze/Test/eth3_triplet"
      model_name: Gaze360
   data:
      image: "/home/xyz/gz/datasets/ETH-XGaze/Image/test"
      label: "/home/xyz/gz/datasets/ETH-XGaze/Label/test.label"


reader: reader_eth
device: 0
