---
train:
  params:
    batch_size: 80
    epoch: 100
    lr: 0.0001
    decay: 1
    decay_step: 5000
    loss: L1Loss
  save:
    save_path: "/home/xyz/gz/GazeBenchmark/GazeZone/TEST/Gaze360"
    model_name: Gaze360
    step: 10
  data:
    image: "/home/xyz/gz/datasets/Gaze360/Image"
    label: "/home/xyz/gz/datasets/Gaze360/Label/train.label"
  pretrains: "None"
test:
   load:
      begin_step: 4
      end_step: 20
      steps: 4
      load_path: "/home/xyz/gz/GazeBenchmark/GazeZone/TEST/Gaze360"
      model_name: PureGaze
   data:
      image: "/home/gaoz/datasets/Gaze360/Image"
      label: "/home/gaoz/datasets/Gaze360/Label/train.label"

reader: reader_gaze360
device: 0
