---
train:
  params:
    batch_size: 80
    epoch: 100
    lr: 0.0001
    decay: 1
    decay_step: 5000
    loss: L1Loss
  save:
    save_path: "/home/xyz/gz/GazeBenchmark/GazeZone/TEST/Gaze360"
    model_name: Gaze360
    step: 10
  data:
    image: "/home/xyz/gz/datasets/Gaze360/Image"
    label: "/home/xyz/gz/datasets/Gaze360/Label/train.label"
  pretrains: "None"
test:
   load:
      begin_step: 4
      end_step: 20
      steps: 4
      load_path: "/home/gaoz/GazeBenchmark/exp/PureGaze/Test/eth3_dataaugment"
      model_name: PureGaze
   data:
      image: "/home/gaoz/datasets/Gaze360/Image"
      label: "/home/gaoz/datasets/Gaze360/Label/train.label"
cross:
  save_name: cross-mpii-new
  load:
      begin_step: 60
      end_step: 60
      steps: 10
      load_path: "/home/cyh/GazeBenchmark/exp/Implementation/Gaze360-gaze360"
      load_name: False
      model_name: Gaze360
  data:
      image: "/home/cyh/GazeDataset20200519/FaceBased/MPIIFaceGaze/Image"
      label: "/home/cyh/GazeDataset20200519/FaceBased/MPIIFaceGaze/Label"

#  image: "/home/cyh/GazeDataset20200519/FaceBased/EyeDiap/Image"
# label: "/home/cyh/GazeDataset20200519/FaceBased/EyeDiap/ClusterLabel"

reader: reader_gaze360
device: 0
