---
train:
  params:
    batch_size: 64
    epoch: 100
    lr: 0.00001
    decay: 0.1
    decay_step: 5000
    loss: L1Loss
  save:
    save_path: "/home/gaoz/GazeBenchmark/Test/GazeZone_K_means"
    model_name: Gaze360
    step: 20
  data:
    image: "/home/gaoz/datasets/EyeDiap/Image"
    label: "/home/gaoz/datasets/EyeDiap/ClusterLabel"
  pretrains: "None"
test:
   load:
      begin_step: 6
      end_step: 6
      steps: 1
      load_path: "/home/xyz/gz/GazeBenchmark/GazeZone/TEST/ETH_0.1_0.01_5"
      model_name: Gaze360
   data:
      image: "/home/xyz/gz/datasets/EyeDiap/Image"
      label: "/home/xyz/gz/datasets/EyeDiap/ClusterLabel"
reader: reader_diap
